repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13  # Replace with the latest version from https://github.com/astral-sh/ruff/releases
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.390
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'PYTHONPATH=$CONDA_PREFIX/lib/python3.12/site-packages pyright'
        language: system
        types: [python]
        require_serial: true

# -   repo: https://github.com/RobertCraigie/pyright-python
#     rev: v1.1.390
#     hooks:
#     - id: pyright